language: ruby
os: linux
before_install:
- sudo apt-get install pandoc
- gem install asciidoctor
script:
- make
after_success:
- ".travis/push.sh"
env:
  global:
    secure: YHAcJSqaQDayrVHa/al622P+yzmpZDa6NHsJRjWLfdYW13hnYgzpVOWEqgUwbCxl06onAmu9d3dz10qZVkvJShIILrF44BfQ5vKhoHcyWWawnSP57KRdVpfPLr8emzhPjcFyOB3st3BewbW7Wm4BxdPPUimdOXwtXB38AxQtTCPQDXj4XrleyTZHUo1+3T1BjGYLG+GwvP9mjW9lzIUKN+FVX9ZPM5irqC3T/pMhMuzcP52G3XtbX3IMggaK147CklpdfPRUvytLMJ3BJ+Sf76RIALmSSdyrrwyQFY+hgrf+F2Aemzg8M0p9+dSDgXyqz0tIYy6okPd2zjUzgGjuVSoUMjXmxce/VcTGHfTwFjoKGlOCZxVHH8+d0lPM8Dn12429Ol6WhAbQdCIYRGwDig5YyESKLx0dWtIqaYXDLx0G4ddc9sE12uVd9zy14aXl7XYVs96GBhrdnDkqRvlpvNu40D4FYswwuJQdkL54XY6JHX8RQbJ7BE2Vvr/J9A6v9VFO63D/cE/PwIQ4vh6g0fqDCZ0yvNFT5gEQhFKGzRqItj9Q8vtvM8z6hfR+VKDQe3HF0E7l9kkRDgFmVQcXMpu96ay6ak353DO6JJbeSXQFoo36xxqUHkgP3zrm1dU4QeGY9KqzzCREshv4xYYYRiqUItXj01p/fESJUbCxJHA=
